# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Employee'), (2, ' Supervisor Production'), (2, 'Supervisor Pinner'), (3, 'Supervisor Quality Checker'), (4, 'Admin')], default=4),
        ),
    ]
